### ISSUE TITLE
Bug with responsive view

### ISSUE THREAD

**Issue by selinav** [tsl143/measure-it#11]
Hello,
Thank you for this addon.

When I try to use it with responsible view, it doesn't work. It works well only with the normal view.
The "+" cursor doesn't appear.
![image](https://user-images.githubusercontent.com/1162603/57458537-d449fb80-7271-11e9-8102-723048d06310.png)

**Comment by tsl143** [comment]
This is a long standing bug, as measure-it uses mouse events and in responsive mode technically there are no mouse events :( 

This can work in responsive mode if you turn off the touch simulations

**Comment by tsl143** [comment]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/5318732/57459901-681cc700-7274-11e9-9bab-8738ebf0c63b.png">
