### ISSUE TITLE
MeasureIt 2.2.0 does not work in FF 70.0.1

### ISSUE THREAD

**Issue by JRTENN** [tsl143/measure-it#13]
Downloaded and installed into Firefox 70.0.1 (Windows) what appears to be latest MeasureIt, version 2.2.0. Does not activate at all on any webpage, nor work like it "used to" in older Firefox versions.

Wish we could see a MeasureIt made for Chrome browsers like SlimJet, and others.

Joe
email: josephrot@yahoo.com

**Comment by tsl143** [comment]
Hi Joe, thank you for reporting.
I tried to reproduce this issue but was not able to do so,
following are the combinations I tried:
Win 7 + FF 70.0.1
![image](https://user-images.githubusercontent.com/5318732/69131990-841ae400-0ab3-11ea-93b5-cdb64aced115.png)

MacOS 10.13 + FF 70.0.1
![image](https://user-images.githubusercontent.com/5318732/69132081-ae6ca180-0ab3-11ea-9f68-3c6fcbda7c01.png)


==================================================================
I can look around more if you can provide console errors (if any) from the `browser console` => `Ctrl + Shift + J`.

**Comment by JRTENN** [comment]
Well..."suddenly" started working, after two resets of Firefox FF 70.0.1 (Windows 7 and 10 OS), and was not related to any video / video chip-set situations.

Could have been that I had just updated Firefox to 70.0.1 from the immediately prevoious version.

Thank you again for the feedback, and I can report that all seems well now.

**ON THE WISH-LIST:**

**Wish we could see a MeasureIt made for Chrome browsers like SlimJet, and others.**

Joe Rotello / WindowGroup
Knoxville, TN

**Comment by tsl143** [comment]
Thanks for verifying!

https://chrome.google.com/webstore/detail/measure-it/jocbgkoackihphodedlefohapackjmna

I feel like Santa rn :P
