### ISSUE TITLE
Can't change the Keyboard shortcut

### ISSUE THREAD

**Issue by PamProg** [tsl143/measure-it#16]
Hello, I can't change the shortcut. Here is what I get when I try :

The default one :
![image](https://user-images.githubusercontent.com/29798978/90657993-54b42600-e243-11ea-96c9-bf19dcc0f857.png)

When I clicked on the input :
![image](https://user-images.githubusercontent.com/29798978/90658036-609fe800-e243-11ea-9bae-334869fbe364.png)

When I input almost any "normal" key  (here, letter F):
![image](https://user-images.githubusercontent.com/29798978/90658080-6c8baa00-e243-11ea-8b79-f6516dd94ee5.png)

Thing is, when I tried to input Alt or Ctrl or Shift, nothing happen.

I'm from France, and so I have a french configured keyboard on a french Windows, so maybe that's the problem.

Thanks :)

**Comment by tsl143** [comment]
Hi, thanks for reporting.
Firefox already implemented native manage shortcuts, please use it to get best results.
Following are the steps:
1. Goto `about:addons`
2. Click gear icon and select `manage extension shortcuts`
3. On the Manage shortcut screen, find measure-it and change it as per your requirement

screen 1
![image](https://user-images.githubusercontent.com/5318732/90723008-33435080-e2bc-11ea-9b3b-9d1b4002ebb3.png)

screen 2
![image](https://user-images.githubusercontent.com/5318732/90723108-70a7de00-e2bc-11ea-8c69-1a9381e77e31.png)

screen 3
![image](https://user-images.githubusercontent.com/5318732/90723063-51a94c00-e2bc-11ea-9f7d-ebd64fcf230f.png)

@PamProg Let me know if it works for you :)

**Comment by PamProg** [comment]
Hello,

I tried it and it worked like a charm !
I didn't know that Firefox could manage it directly, that's a nice feature.
Thank you ! :)
