### ISSUE TITLE
Add user preferences

### ISSUE THREAD

**Issue by tsl143** [tsl143/measure-it#3]
User should be able to change color/opacity of overlay, measure box.

**Comment by worldsdream** [comment]
Thats what we all want to see. Looking forward to it. 
Please close this issue when it is added to the plugin! So I am up to date.

**Comment by tsl143** [comment]
Almost a year, but its done! (Chrome and firefox v2.1.0)

**Comment by worldsdream** [comment]
So nice. Great job @tsl143 !!!
