### ISSUE TITLE
Size text color uses the body color

### ISSUE THREAD

**Issue by j-oliveras** [tsl143/measure-it#6]
The size span uses the color from body element. That causes that if a webside has the body css property `color` as white the sizes is not displayed.
![screen](https://user-images.githubusercontent.com/15308683/44860361-4e9f9600-ac76-11e8-8c30-98cab7644e79.PNG)
To reproduce:
* A website that the body has the property `color` `white`.
* Use the extension.

**Comment by j-oliveras** [comment]
I use the version 2.0.1.

**Comment by j-oliveras** [comment]
This seems solved at master:
https://github.com/tsl143/measure-it/blob/master/cs.js#L65
https://github.com/tsl143/measure-it/blob/master/cs.js#L74

The version 2.0.1 has an old version of cs.js.

**Comment by tsl143** [comment]
Thanks @j-oliveras for motivating me, I needed few more fixes for labels, hence didn't update it, but now the new version is updated with the changes :)
V2.0.3
Thanks again :)

**Comment by j-oliveras** [comment]
Thanks, now works.
