### ISSUE TITLE
Feature request: ability to change the trigger shortcut

### ISSUE THREAD

**Issue by andersonpem** [tsl143/measure-it#7]
Hello. Thanks for this extension.
I'd like to suggest the ability to change the shortcut of the extension. As you (probably) know, ctrl+shift+m triggers the mobile environment enforcement on Firefox. That's nice for testing if your site is responsive when in development.
It'd be nice to change the extension shortcut so it would not conflict with mozilla's one.
Thanks :)

**Comment by tsl143** [comment]
Hi @andersonpem Thanks for inputs, it really is a problem when we dont have shortcut for responsive mode, I changed the shortcut back to `Alt+shift+m`

The problem with giving options for user to select shortcut is, for this I have to inject JS in page which will initiate the whole function, and for that extension will require unnecessary permissions `Addon wants to access all data of websites` that's kinda scary.
If you find something that can help this situation, I will be more than happy to do it :) 
Once again thanks :)

**Comment by tsl143** [comment]
@andersonpem , So Firefox now provide command update which I can use for custom shortcuts.
Meanwhile enjoy the new preferences in 2.1.0.

**Comment by tsl143** [comment]
This has been implemented in 2.1.1.
