### ISSUE TITLE
Feature request: show sizes inside the rectangle

### ISSUE THREAD

**Issue by immwi** [tsl143/measure-it#9]
I often measure viewport's inner width and I stretch the measure-it margins until the browser borders. The size-tags happen to be displayed outside the window borders, invisible.
I'd be happy to see the size calculations even in these situations.
Suggestion: show size-tags inside the measurement rectangle, after a certain size.

Thank you!!

**Comment by tsl143** [comment]
Thanks for reporting,
I am trying to make it more smart , when it goes to borders measurements will move inside in box.

**Comment by tsl143** [comment]
This has been implemented in version 2.1.1
